Repository OpenIntelWireless/HeliPort, pull requests merged in 2020-07, with the labels that each got.

#39 Check if itlwm is loaded at startup
  HeliPort/AppDelegate.swift
Labels: enhancement

#37 Added support to check if SSID is connected
  ClientKit/Api.c
  Common/Common.h
  HeliPort/Appearance/StatusMenu.swift
  HeliPort/NetworkInfo.swift
Labels: enhancement

#48 Italian and Turkish languages
  HeliPort.xcodeproj/project.pbxproj
  HeliPort/Appearance/it.lproj/Localizable.strings
  HeliPort/Appearance/tr.lproj/Localizable.strings
Labels: documentation, enhancement

#47 Status bar correctly reflects the strength of the connected network
  ClientKit/Api.c
  HeliPort.xcodeproj/project.pbxproj
  HeliPort/AppDelegate.swift
  HeliPort/Appearance/StatusBarIconManager.swift
  HeliPort/Appearance/StatusMenu.swift
  HeliPort/Appearance/WiFiMenuItemView.swift
Labels: enhancement

#54 Update Spanish translations
  HeliPort/Appearance/es.lproj/Localizable.strings
Labels: documentation, enhancement

#51 Introduce Greek language
  HeliPort.xcodeproj/project.pbxproj
  HeliPort/Appearance/el.lproj/Localizable.strings
Labels: documentation, enhancement

#61 Fixed issue with text wrapping WiFiMenuItemView.
  HeliPort/Appearance/StatusBarIconManager.swift
  HeliPort/Appearance/StatusMenu.swift
  HeliPort/Appearance/WiFiMenuItemView.swift
  HeliPort/Assets.xcassets/WiFiStateError.imageset/Contents.json
  HeliPort/Assets.xcassets/WiFiStateError.imageset/WiFiStateError.png
  HeliPort/Assets.xcassets/WiFiStateError.imageset/WiFiStateError@2x.png
  HeliPort/Assets.xcassets/WiFiStateScanning1.imageset/Contents.json
  HeliPort/Assets.xcassets/WiFiStateScanning1.imageset/WiFiStateScanning1.png
  HeliPort/Assets.xcassets/WiFiStateScanning1.imageset/WiFiStateScanning1@2x.png
  HeliPort/Assets.xcassets/WiFiStateScanning2.imageset/Contents.json
  HeliPort/Assets.xcassets/WiFiStateScanning2.imageset/WiFiStateScanning2.png
  HeliPort/Assets.xcassets/WiFiStateScanning2.imageset/WiFiStateScanning2@2x.png
  HeliPort/Assets.xcassets/WiFiStateScanning3.imageset/Contents.json
  HeliPort/Assets.xcassets/WiFiStateScanning3.imageset/WiFiStateScanning3.png
  HeliPort/Assets.xcassets/WiFiStateScanning3.imageset/WiFiStateScanning3@2x.png
  HeliPort/Assets.xcassets/WiFiStateScanning4.imageset/Contents.json
  HeliPort/Assets.xcassets/WiFiStateScanning4.imageset/WiFiStateScanning4.png
  HeliPort/Assets.xcassets/WiFiStateScanning4.imageset/WiFiStateScanning4@2x.png
  HeliPort/Assets.xcassets/WiFiStateWarning.imageset/Contents.json
  HeliPort/Assets.xcassets/WiFiStateWarning.imageset/WiFiStateWarning.png
  HeliPort/Assets.xcassets/WiFiStateWarning.imageset/WiFiStateWarning@2x.png
Labels: enhancement

#52 Refactoring network manager
  HeliPort.xcodeproj/project.pbxproj
  HeliPort/AppDelegate.swift
  HeliPort/Appearance/JoinPopWindow.swift
  HeliPort/Appearance/StatusBarIconManager.swift
  HeliPort/Appearance/StatusMenu.swift
  HeliPort/Appearance/WiFiMenuItemView.swift
  HeliPort/Appearance/WiFiPopoverView.swift
  HeliPort/NetworkManager+Data.swift
  HeliPort/NetworkManager.swift
  HeliPort/Supporting files/itl80211_security+Description.swift
  HeliPort/Supporting files/itl_80211_state+Description.swift
  HeliPort/Supporting files/itl_phy_mode+Description.swift
Labels: enhancement

#65 Add Korean localization
  HeliPort.xcodeproj/project.pbxproj
  HeliPort/Appearance/ko.lproj/Localizable.strings
Labels: documentation

#62 Added german Translation
  HeliPort.xcodeproj/project.pbxproj
  HeliPort/Appearance/de.lproj/Localizable.strings
Labels: documentation

#59 Add Russian Language
  HeliPort.xcodeproj/project.pbxproj
  HeliPort/Appearance/ru.lproj/Localizable.strings
Labels: documentation

#69 Add Polish translation
  HeliPort.xcodeproj/project.pbxproj
  HeliPort/Appearance/pl.lproj/Localizable.strings
Labels: documentation

#68 Add Vietnamese language!
  HeliPort.xcodeproj/project.pbxproj
  HeliPort/Appearance/vi.lproj/Localizable.strings
Labels: documentation

#72 Widen some labels to fit localized text
  HeliPort/Appearance/JoinPopWindow.swift
Labels: bug

#56 Auto-connect saved networks on start
  HeliPort/Appearance/JoinPopWindow.swift
  HeliPort/Appearance/StatusMenu.swift
  HeliPort/CredentialsManager.swift
  HeliPort/NetworkManager+Data.swift
  HeliPort/NetworkManager.swift
  HeliPort/Supporting files/itl80211_security+Description.swift
Labels: enhancement

#77 Switching to Apple stock translation (Italian)
  HeliPort/Appearance/it.lproj/Localizable.strings
Labels: documentation

#75 Adding Portuguese (Portugal) language
  HeliPort.xcodeproj/project.pbxproj
  HeliPort/Appearance/pt-PT.lproj/Localizable.strings
Labels: documentation

#73 API fixes & improvement
  ClientKit/Api.c
Labels: enhancement

#83 Greek missing autorun text
  HeliPort/Appearance/el.lproj/Localizable.strings
Labels: documentation

#82 Add a few "Launch At Login" translations
  HeliPort/Appearance/de.lproj/Localizable.strings
  HeliPort/Appearance/es.lproj/Localizable.strings
  HeliPort/Appearance/fr.lproj/Localizable.strings
  HeliPort/Appearance/it.lproj/Localizable.strings
  HeliPort/Appearance/ko.lproj/Localizable.strings
  HeliPort/Appearance/pl.lproj/Localizable.strings
Labels: documentation

#84 Update Italian
  HeliPort/Appearance/it.lproj/Localizable.strings
Labels: documentation

#85 Update Portuguese (Portugal) typos and add missing translations
  HeliPort/Appearance/pt-PT.lproj/Localizable.strings
Labels: documentation

#86 Fix translations
  HeliPort/Appearance/de.lproj/Localizable.strings
  HeliPort/Appearance/el.lproj/Localizable.strings
  HeliPort/Appearance/es.lproj/Localizable.strings
  HeliPort/Appearance/fr.lproj/Localizable.strings
  HeliPort/Appearance/it.lproj/Localizable.strings
  HeliPort/Appearance/ko.lproj/Localizable.strings
  HeliPort/Appearance/pl.lproj/Localizable.strings
  HeliPort/Appearance/pt-BR.lproj/Localizable.strings
  HeliPort/Appearance/pt-PT.lproj/Localizable.strings
  HeliPort/Appearance/ru.lproj/Localizable.strings
  HeliPort/Appearance/tr.lproj/Localizable.strings
  HeliPort/Appearance/vi.lproj/Localizable.strings
  HeliPort/Appearance/zh-Hans.lproj/Localizable.strings
Labels: documentation

#93 TR - Fix Translations
  HeliPort/Appearance/tr.lproj/Localizable.strings
Labels: documentation

#95 Bug: Correction and translation to pt-BR
  HeliPort/Appearance/pt-BR.lproj/Localizable.strings
Labels: bug, documentation

#90 Autojoin enabled/disabled on disconnect/connect, no frozen Keychain auth
  HeliPort/Appearance/StatusMenu.swift
  HeliPort/CredentialsManager.swift
  HeliPort/NetworkManager.swift
Labels: enhancement

#96 Update Vietnamese Localizable.strings
  HeliPort/Appearance/vi.lproj/Localizable.strings
Labels: documentation

#89 Added reachability/error callback, improvements on StatusMenu layout
  HeliPort/Appearance/StatusBarIconManager.swift
  HeliPort/Appearance/StatusMenu.swift
  HeliPort/NetworkManager.swift
  HeliPort/Supporting files/itl_80211_state+Description.swift
Labels: enhancement

#100 Fix Vietnamese translation errors
  HeliPort/Appearance/vi.lproj/Localizable.strings
Labels: bug, documentation

#103 Fix missing greek texts
  HeliPort/Appearance/el.lproj/Localizable.strings
Labels: documentation

#87 Checks on itlwm
  HeliPort/AppDelegate.swift
Labels: enhancement

#97 Refactor hidden items
  HeliPort/Appearance/StatusMenu.swift
Labels: enhancement

#94 Refactor Connected Network Item
  ClientKit/Api.c
  ClientKit/Api.h
  HeliPort/Appearance/StatusMenu.swift
  HeliPort/Appearance/WiFiMenuItemView.swift
  HeliPort/NetworkManager.swift
  HeliPort/Supporting files/NetworkManager+Data.swift
Labels: enhancement

#110 SSID now shows immediately upon opening Heliport
  HeliPort/Appearance/StatusMenu.swift
Labels: enhancement

#120 Update and add Portuguese (Portugal) translations
  HeliPort/Appearance/pt-PT.lproj/Localizable.strings
Labels: documentation

#122 Update German localization
  HeliPort/Appearance/de.lproj/Localizable.strings
Labels: documentation

#118 Fixed getting router IP from itlwm interface
  HeliPort/NetworkManager.swift
Labels: enhancement

#126 Simpler alert creation and text localization
  HeliPort.xcodeproj/project.pbxproj
  HeliPort/AppDelegate.swift
  HeliPort/Appearance/JoinPopWindow.swift
  HeliPort/Appearance/StatusMenu.swift
  HeliPort/Appearance/WiFiPopoverView.swift
  HeliPort/NetworkManager.swift
  HeliPort/Supporting files/Alert.swift
  HeliPort/Supporting files/NSLocalizedString+Extensions.swift
Labels: enhancement

#125 Texting improvements
  HeliPort/Appearance/es.lproj/Localizable.strings
  HeliPort/Credits.rtf
Labels: documentation

#136 Added bug reporter functionality
  HeliPort.xcodeproj/project.pbxproj
  HeliPort/Appearance/StatusMenu.swift
  HeliPort/NetworkManager.swift
  HeliPort/Supporting files/BugReporter.swift
  HeliPort/Supporting files/Commands.swift
  HeliPort/Supporting files/Log.swift
Labels: enhancement

#138 Added Indonesian language
  HeliPort.xcodeproj/project.pbxproj
  HeliPort/Appearance/id.lproj/Localizable.strings
Labels: documentation

#139 Fixed OSLog not showing info on release builds
  HeliPort/Supporting files/BugReporter.swift
  HeliPort/Supporting files/Log.swift
Labels: enhancement

#140 Update French Translation
  HeliPort/Appearance/fr.lproj/Localizable.strings
Labels: documentation
