Repository OpenIntelWireless/HeliPort, pull requests merged in 2020-06, with the labels that each got.

#10 I18n
  .gitignore
  ClientKit/Api.c
  HeliPort.xcodeproj/project.pbxproj
  HeliPort/Appearance/JoinPopWindow.swift
  HeliPort/Appearance/StatusMenu.swift
  HeliPort/Appearance/WiFiPopoverView.swift
  HeliPort/Appearance/zh-Hans.lproj/Localizable.strings
  HeliPort/Appearance/zh-Hans.lproj/MainMenu.strings
Labels: enhancement

#14 Add Sparkle updater framework
  .github/prepRelease.sh
  .github/sparkleAppcast.sh
  .github/workflows/main.yml
  .gitignore
  HeliPort.xcodeproj/project.pbxproj
  HeliPort.xcworkspace/contents.xcworkspacedata
  HeliPort/Appearance/Base.lproj/MainMenu.xib
  HeliPort/Appearance/StatusMenu.swift
  HeliPort/Appearance/zh-Hans.lproj/Localizable.strings
  HeliPort/HeliPort.entitlements
  HeliPort/Info.plist
  Podfile
  Podfile.lock
Labels: enhancement

#19 Implement PlistManager to store user info
  HeliPort.xcodeproj/project.pbxproj
  HeliPort/WifiPlistManager.swift
Labels: enhancement

#20 Fixed issue when 8 characters on password would not allow to join.
  HeliPort/Appearance/JoinPopWindow.swift
Labels: bug, enhancement

#24 Added support for " Show "Wi-Fi: Looking for Networks..." when itlwm …
  ClientKit/Api.c
  HeliPort/Appearance/StatusMenu.swift
  HeliPort/Appearance/WiFiMenuItemView.swift
Labels: bug, enhancement

#28 French README.md
  .github/README_fr.md
Labels: documentation

#30 Basic functionality to save and load passwords
  .swiftlint.yml
  HeliPort.xcodeproj/project.pbxproj
  HeliPort/Appearance/StatusMenu.swift
  HeliPort/Appearance/WiFiPopoverView.swift
  HeliPort/Appearance/WifiPopupWindow.swift
  HeliPort/CredentialsManager.swift
  HeliPort/KeychainManager.swift
  HeliPort/Log.swift
  HeliPort/NetworkInfo.swift
  Podfile
  Podfile.lock
Labels: enhancement

#38 JoinWindowPopup improvements
  HeliPort/Appearance/JoinPopWindow.swift
Labels: enhancement

#34 Update power state
  ClientKit/Api.c
  ClientKit/Api.h
  HeliPort/Appearance/StatusBarIconManager.swift
  HeliPort/Appearance/StatusMenu.swift
  HeliPort/NetworkInfo.swift
Labels: enhancement

#35 Status menu code quality improvements
  HeliPort.xcodeproj/project.pbxproj
  HeliPort/AppDelegate.swift
  HeliPort/Appearance/JoinPopWindow.swift
  HeliPort/Appearance/StatusMenu.swift
  HeliPort/Supporting files/Log.swift
  HeliPort/Supporting files/NSMenuItem+Extensions.swift
  HeliPort/Supporting files/itl_80211_state+Status.swift
Labels: enhancement
