Repository OpenIntelWireless/HeliPort, pull requests merged in 2024-07, with the labels that each got.

#258 Fix warnings related to deallocating CriticalAlert prematurely
  HeliPort/Supporting files/BugReporter.swift
Labels: bug

#260 Updated and added Localizable.strings for Vietnamese
  HeliPort/Appearance/vi.lproj/Localizable.strings
Labels: i18n

#261 Migrate to Sparkle 2
  .github/workflows/main.yml
  HeliPort.xcodeproj/project.pbxproj
  HeliPort/Appearance/Preferences/PrefsGeneralView.swift
  HeliPort/Appearance/StatusMenu.swift
  HeliPort/Info.plist
  HeliPort/UpdateManager.swift
Labels: enhancement
